import type { Metadata } from "next";
import "./globals.css";
import ThemeContainer from "./themeContainer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <ThemeContainer>
      <body>
        {children}
      </body>
      </ThemeContainer>
    </html>
  );
}
